;;; centaur-tabs-vertical-test.el --- Tests for centaur-tabs-vertical -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(let* ((this-file (or load-file-name buffer-file-name))
       (test-dir (file-name-directory this-file))
       (project-dir (directory-file-name (file-name-directory (directory-file-name test-dir))))
       (repo-dir (directory-file-name (file-name-directory project-dir))))
  (add-to-list 'load-path project-dir)
  (add-to-list 'load-path repo-dir))

(require 'centaur-tabs-vertical)

(defun centaur-tabs-vertical-test--face-raise (face)
  "Return the :raise value from FACE or nil."
  (cond
   ((and (listp face) (plist-member face :raise))
    (plist-get face :raise))
   ((listp face)
    (cl-loop for entry in face
             for value = (centaur-tabs-vertical-test--face-raise entry)
             when value return value))
   (t nil)))

(ert-deftest centaur-tabs-vertical-pad ()
  (let ((result (centaur-tabs-vertical--pad "abc" 5 'default)))
    (should (= (string-width result) 5))
    (should (equal (substring result 0 3) "abc")))
  (let ((result (centaur-tabs-vertical--pad "abcdef" 3 'default)))
    (should (= (string-width result) 3))))

(ert-deftest centaur-tabs-vertical-tab-label ()
  (let ((centaur-tabs-tab-label-function (lambda (_tab) "X")))
    (should (equal (centaur-tabs-vertical--tab-label (cons (current-buffer) nil)) "X"))))

(ert-deftest centaur-tabs-vertical-render-tab-properties ()
  (with-temp-buffer
    (let* ((buf (current-buffer))
           (tab (cons buf 'dummy))
           (centaur-tabs-vertical-show-icons nil)
           (centaur-tabs-set-icons nil)
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil))
      (let ((left (centaur-tabs-vertical--render-tab tab tab 'left 10)))
        (should (= (string-width left) 12))
        (should (eq (get-text-property 0 'centaur-tabs-tab left) tab)))
      (let ((right (centaur-tabs-vertical--render-tab tab tab 'right 10)))
        (should (= (string-width right) 12))
        (should (eq (get-text-property 1 'centaur-tabs-tab right) tab))))))

(ert-deftest centaur-tabs-vertical-render-tab-truncates-with-wide-icon ()
  (with-temp-buffer
    (let* ((buf (current-buffer))
           (tab (cons buf 'dummy))
           (label "abcdefgh")
           (centaur-tabs-tab-label-function (lambda (_tab) label))
           (centaur-tabs-vertical-show-icons t)
           (centaur-tabs-set-icons t)
           (centaur-tabs--buffer-show-groups nil)
           (centaur-tabs-set-close-button t)
           (centaur-tabs-set-left-close-button nil)
           (centaur-tabs-close-button "x")
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil))
      (cl-letf (((symbol-function 'centaur-tabs-icon)
                 (lambda (_tab _face _selected)
                   (propertize " " 'display '(space :width 2))))
                ((symbol-function 'string-pixel-width)
                 (lambda (text)
                   (if (get-text-property 0 'display text)
                       20
                     (* 10 (string-width text)))))
                ((symbol-function 'frame-char-width)
                 (lambda () 10)))
        (let ((rendered (centaur-tabs-vertical--render-tab tab tab 'left 12)))
          (should (not (string-match (regexp-quote label) rendered))))))))

(ert-deftest centaur-tabs-vertical-render-tab-dead-buffer ()
  (let ((buf (generate-new-buffer " *ctv-dead*")))
    (kill-buffer buf)
    (let* ((tab (cons buf 'dummy))
           (centaur-tabs-vertical-show-icons nil)
           (centaur-tabs-set-icons nil)
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil)
           (rendered (centaur-tabs-vertical--render-tab tab tab 'left 10)))
      (should (equal rendered "")))))

(ert-deftest centaur-tabs-vertical-select-replacement-tab ()
  (let ((buf1 (generate-new-buffer " *ctv-a*"))
        (buf2 (generate-new-buffer " *ctv-b*")))
    (unwind-protect
        (let* ((tab1 (cons buf1 'dummy))
               (tab2 (cons buf2 'dummy))
               selected)
          (cl-letf (((symbol-function 'centaur-tabs-current-tabset)
                     (lambda (&rest _) 'tabset))
                    ((symbol-function 'centaur-tabs-tabs)
                     (lambda (_tabset) (list tab1 tab2)))
                    ((symbol-function 'centaur-tabs-buffer-select-tab)
                     (lambda (tab) (setq selected tab))))
            (with-current-buffer buf1
              (centaur-tabs-vertical--maybe-select-replacement tab1))
            (should (eq selected tab2))))
      (when (buffer-live-p buf1) (kill-buffer buf1))
      (when (buffer-live-p buf2) (kill-buffer buf2)))))

(ert-deftest centaur-tabs-vertical-close-tab-fallback-buffer ()
  (let ((buf1 (generate-new-buffer "ctv-main"))
        (buf2 (generate-new-buffer "ctv-fallback"))
        (side (generate-new-buffer " *centaur-tabs-vertical-left*")))
    (unwind-protect
        (let* ((tab1 (cons buf1 'dummy))
               (set-called nil)
               (closed nil))
          (cl-letf (((symbol-function 'centaur-tabs-current-tabset)
                     (lambda (&rest _) 'tabset))
                    ((symbol-function 'centaur-tabs-tabs)
                     (lambda (_tabset) (list tab1)))
                    ((symbol-function 'centaur-tabs-buffer-select-tab)
                     (lambda (_tab) (error "should not select neighbor")))
                    ((symbol-function 'buffer-list)
                     (lambda (&optional _frame) (list buf1 side buf2)))
                    ((symbol-function 'set-window-buffer)
                     (lambda (_win buffer) (setq set-called buffer)))
                    ((symbol-function 'centaur-tabs-buffer-close-tab)
                     (lambda (_tab) (setq closed t))))
            (with-current-buffer buf1
              (centaur-tabs-vertical--close-tab tab1))
            (should (eq set-called buf2))
            (should closed)))
      (when (buffer-live-p buf1) (kill-buffer buf1))
      (when (buffer-live-p buf2) (kill-buffer buf2))
      (when (buffer-live-p side) (kill-buffer side)))))

(ert-deftest centaur-tabs-vertical-buffer-list-excludes-side ()
  (let ((buf1 (generate-new-buffer "ctv-main"))
        (side (generate-new-buffer " *centaur-tabs-vertical-left*")))
    (unwind-protect
        (let ((centaur-tabs-vertical--saved-buffer-list-function
               (lambda () (list buf1 side))))
          (should (equal (centaur-tabs-vertical--buffer-list) (list buf1))))
      (when (buffer-live-p buf1) (kill-buffer buf1))
      (when (buffer-live-p side) (kill-buffer side)))))

(ert-deftest centaur-tabs-vertical-advice-line ()
  (let ((centaur-tabs-vertical-mode t))
    (should (null (centaur-tabs-vertical--advice-line (lambda (&rest _) 'ok)))))
  (let ((centaur-tabs-vertical-mode nil))
    (should (equal (centaur-tabs-vertical--advice-line (lambda (&rest _) 'ok)) 'ok))))

(ert-deftest centaur-tabs-vertical-interactive-toggle-commands ()
  (let (calls)
    (cl-letf (((symbol-function 'centaur-tabs-vertical-mode)
               (lambda (&optional arg) (push arg calls))))
      (centaur-tabs-vertical-enable)
      (centaur-tabs-vertical-disable))
    (should (equal (nreverse calls) '(1 0)))))

(ert-deftest centaur-tabs-vertical-close-button-properties ()
  (with-temp-buffer
    (let* ((buf (current-buffer))
           (tab (cons buf 'dummy))
           (centaur-tabs-set-close-button t)
           (centaur-tabs-set-left-close-button t)
           (centaur-tabs-close-button "x")
           (centaur-tabs-vertical-show-icons nil)
           (centaur-tabs-set-icons nil)
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil))
      (let* ((rendered (centaur-tabs-vertical--render-tab tab tab 'left 12))
             (first (string-match (regexp-quote centaur-tabs-close-button) rendered))
             (last (cl-search centaur-tabs-close-button rendered :from-end t))
             (left-map (and first (get-text-property first 'local-map rendered)))
             (right-map (and last (get-text-property last 'local-map rendered))))
        (should (eq left-map centaur-tabs-vertical-close-map))
        (should (eq right-map centaur-tabs-vertical-close-map))))))

(ert-deftest centaur-tabs-vertical-close-align-spacer-no-pad ()
  (with-temp-buffer
    (rename-buffer "abc" t)
    (let* ((buf (current-buffer))
           (tab (cons buf 'dummy))
           (centaur-tabs-set-close-button t)
           (centaur-tabs-set-left-close-button nil)
           (centaur-tabs-close-button "x")
           (centaur-tabs-vertical-show-icons nil)
           (centaur-tabs-set-icons nil)
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil)
           (rendered (centaur-tabs-vertical--render-tab tab tab 'left 20))
           (align-index (cl-loop for i from 0 below (length rendered)
                                 for disp = (get-text-property i 'display rendered)
                                 when (and (consp disp) (eq (car disp) 'space))
                                 do (cl-return i))))
      (should align-index)
      (should (not (eq (aref rendered (1- align-index)) ?\s))))))

(ert-deftest centaur-tabs-vertical-new-tab-button-properties ()
  (let* ((centaur-tabs-vertical-show-new-tab-button t)
         (centaur-tabs-new-tab-text " + ")
         (width 20)
         (rendered (centaur-tabs-vertical--render-new-tab 'left width))
         (pos (string-match (regexp-quote centaur-tabs-new-tab-text) rendered)))
    (should pos)
    (should (eq (get-text-property 0 'local-map rendered)
                centaur-tabs-vertical-new-tab-map))
    (should (eq (get-text-property (1- width) 'local-map rendered)
                centaur-tabs-vertical-new-tab-map))
    (should (eq (get-text-property pos 'local-map rendered)
                centaur-tabs-vertical-new-tab-map))))

(ert-deftest centaur-tabs-vertical-new-tab-button-centered ()
  (let* ((centaur-tabs-vertical-show-new-tab-button t)
         (centaur-tabs-new-tab-text " + ")
         (width 20)
         (rendered (centaur-tabs-vertical--render-new-tab 'left width))
         (pos (string-match (regexp-quote centaur-tabs-new-tab-text) rendered))
         (button-width (string-width centaur-tabs-new-tab-text))
         (expected (floor (/ (- width button-width) 2))))
    (should pos)
    (should (= pos expected))))

(ert-deftest centaur-tabs-vertical-navigation-buttons-properties ()
  (let* ((centaur-tabs-vertical-show-navigation-buttons t)
         (centaur-tabs-show-navigation-buttons t)
         (centaur-tabs-down-tab-text " v ")
         (centaur-tabs-backward-tab-text " < ")
         (centaur-tabs-forward-tab-text " > ")
         (width 30))
    (cl-letf (((symbol-function 'display-graphic-p)
               (lambda (&optional _frame) t)))
      (let* ((rendered (centaur-tabs-vertical--render-navigation 'left width))
             (down-pos (string-match (regexp-quote centaur-tabs-down-tab-text) rendered))
             (back-pos (string-match (regexp-quote centaur-tabs-backward-tab-text) rendered))
             (forward-pos (string-match (regexp-quote centaur-tabs-forward-tab-text) rendered)))
        (should down-pos)
        (should back-pos)
        (should forward-pos)
        (should (eq (get-text-property down-pos 'local-map rendered)
                    centaur-tabs-vertical-down-tab-map))
        (should (eq (get-text-property back-pos 'local-map rendered)
                    centaur-tabs-vertical-backward-tab-map))
        (should (eq (get-text-property forward-pos 'local-map rendered)
                    centaur-tabs-vertical-forward-tab-map))))))

(ert-deftest centaur-tabs-vertical-navigation-buttons-disabled-in-tty ()
  (let* ((centaur-tabs-vertical-show-navigation-buttons t)
         (centaur-tabs-show-navigation-buttons t))
    (cl-letf (((symbol-function 'display-graphic-p)
               (lambda (&optional _frame) nil)))
      (should (null (centaur-tabs-vertical--render-navigation 'left 30))))))

(ert-deftest centaur-tabs-vertical-line-spacing-custom ()
  (let ((centaur-tabs-vertical-line-spacing 2))
    (with-temp-buffer
      (centaur-tabs-vertical-tablist-mode)
      (should (equal line-spacing 2)))))

(ert-deftest centaur-tabs-vertical-line-spacing-match ()
  (let ((centaur-tabs-vertical-line-spacing 'match)
        (centaur-tabs-height 24))
    (cl-letf (((symbol-function 'frame-char-height)
               (lambda (&optional _frame) 18)))
      (with-temp-buffer
        (centaur-tabs-vertical-tablist-mode)
        (should (= line-spacing 6))))))

(ert-deftest centaur-tabs-vertical-line-raise-direction ()
  (let ((centaur-tabs-vertical-line-spacing 4))
    (should (= (centaur-tabs-vertical--line-raise) -2))))

(ert-deftest centaur-tabs-vertical-line-raise-applied ()
  (with-temp-buffer
    (let* ((buf (current-buffer))
           (tab (cons buf 'dummy))
           (centaur-tabs-set-close-button t)
           (centaur-tabs-set-left-close-button t)
           (centaur-tabs-close-button "x")
           (centaur-tabs-vertical-show-icons nil)
           (centaur-tabs-set-icons nil)
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil)
           (centaur-tabs-vertical-line-spacing 4)
           (rendered (centaur-tabs-vertical--render-tab tab tab 'left 12))
           (pos (string-match (regexp-quote centaur-tabs-close-button) rendered))
           (raise (and pos
                       (centaur-tabs-vertical-test--face-raise
                        (get-text-property pos 'face rendered)))))
      (should pos)
      (should (= raise (centaur-tabs-vertical--line-raise))))))

(ert-deftest centaur-tabs-vertical-tab-mouse-face-optional ()
  (with-temp-buffer
    (rename-buffer "abc" t)
    (let* ((buf (current-buffer))
           (tab (cons buf 'dummy))
           (centaur-tabs-vertical-show-icons nil)
           (centaur-tabs-set-icons nil)
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil)
           (centaur-tabs-vertical-mouse-face nil)
           (rendered (centaur-tabs-vertical--render-tab tab tab 'left 12))
           (pos (string-match "abc" rendered)))
      (should pos)
      (should (null (get-text-property pos 'mouse-face rendered))))
    (let* ((buf (current-buffer))
           (tab (cons buf 'dummy))
           (centaur-tabs-vertical-show-icons nil)
           (centaur-tabs-set-icons nil)
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil)
           (centaur-tabs-vertical-mouse-face 'highlight)
           (rendered (centaur-tabs-vertical--render-tab tab tab 'left 12))
           (pos (string-match "abc" rendered)))
      (should pos)
      (should (eq (get-text-property pos 'mouse-face rendered) 'highlight)))))

(ert-deftest centaur-tabs-vertical-group-entry-properties ()
  (let* ((rendered (centaur-tabs-vertical--render-group-entry "GroupA" t 'left 20))
         (pos (string-match "GroupA" rendered)))
    (should pos)
    (should (equal (get-text-property pos 'centaur-tabs-vertical-group rendered) "GroupA"))
    (should (eq (get-text-property pos 'local-map rendered)
                centaur-tabs-vertical-group-map))))

(ert-deftest centaur-tabs-vertical-render-groups-list ()
  (cl-letf (((symbol-function 'centaur-tabs-get-groups)
             (lambda () '("A" "B")))
            ((symbol-function 'centaur-tabs-vertical--current-group-name)
             (lambda () "B")))
    (let ((lines (centaur-tabs-vertical--render-groups 'left 20)))
      (should (= (length lines) 2))
      (should (string-match "A" (nth 0 lines)))
      (should (string-match "B" (nth 1 lines))))))

(ert-deftest centaur-tabs-vertical-cleanup-force ()
  (let ((centaur-tabs-vertical-positions '(left))
        deleted
        killed)
    (cl-letf (((symbol-function 'get-buffer)
               (lambda (name) name))
              ((symbol-function 'get-buffer-window)
               (lambda (_buf) 'dummy-window))
              ((symbol-function 'window-live-p)
               (lambda (_win) t))
              ((symbol-function 'buffer-live-p)
               (lambda (_buf) t))
              ((symbol-function 'delete-window)
               (lambda (win) (push win deleted)))
              ((symbol-function 'kill-buffer)
               (lambda (buf) (push buf killed))))
      (centaur-tabs-vertical--cleanup-windows t)
      (should (= (length deleted) 2))
      (should (= (length killed) 2))
      (should (member (centaur-tabs-vertical--buffer-name 'left) killed))
      (should (member (centaur-tabs-vertical--buffer-name 'right) killed)))))

(ert-deftest centaur-tabs-vertical-close-align-when-truncated ()
  (with-temp-buffer
    (rename-buffer "very-long-buffer-name-that-should-truncate" t)
    (let* ((buf (current-buffer))
           (tab (cons buf 'dummy))
           (centaur-tabs-set-close-button t)
           (centaur-tabs-set-left-close-button nil)
           (centaur-tabs-close-button "x")
           (centaur-tabs-vertical-show-icons nil)
           (centaur-tabs-set-icons nil)
           (centaur-tabs-vertical-show-modified-marker nil)
           (centaur-tabs-set-modified-marker nil)
           (rendered (centaur-tabs-vertical--render-tab tab tab 'left 12))
           (align-index (cl-loop for i from 0 below (length rendered)
                                 for disp = (get-text-property i 'display rendered)
                                 when (and (consp disp) (eq (car disp) 'space))
                                 do (cl-return i)))
           (close-index (cl-search centaur-tabs-close-button rendered :from-end t)))
      (should align-index)
      (should close-index)
      (should (< align-index close-index))
      (should (not (string-match-p (regexp-quote (buffer-name buf)) rendered))))))
