;; -*- mode: eask; lexical-binding: t -*-

(package "centaur-tabs-vertical"
         "0.1.0"
         "Vertical side tabs for centaur-tabs")

(website-url "https://github.com/Kyure-A/centaur-tabs-vertical")
(keywords "frames" "convenience")

(package-file "centaur-tabs-vertical.el")

(script "test" "eask test ert ./test/*.el")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "27.1")
(depends-on "centaur-tabs" "3.3")

(setq network-security-level 'low)
